apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: mission-critical 
value: 999998
globalDefault: false
description: "Critical pods besides the kube-system"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal
value: 900000
globalDefault: false
description: "Normal"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: not-important
value: 800000
globalDefault: false
description: "Not good, but can be down for some time"